config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :gyms, except: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gym.rb
class Gym < ApplicationRecord
  validates :name, presence: true
  validates :amount_of_times, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :set_gym, only: %i[edit update destroy]

  def index
    @gyms = Gym.all
  end

  def new
    @gym = Gym.new
  end

  def create
    @gym = Gym.new(gym_params)

    if @gym.save
      redirect_to gyms_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @gym.update(gym_params)
      redirect_to gyms_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @gym.destroy

    redirect_to gyms_path, status: :see_other
  end

  private

  def set_gym
    @gym = Gym.find(params[:id])
  end

  def gym_params
    params.require(:gym).permit(:name, :address, :amount_of_times)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gyms/_form.html.erb
<%= simple_form_for(gym) do |f| %>
  <%= f.input :name, label: "Nome" %>
  <%= f.input :amount_of_times, label: "Idas por mês" %>
  <%= f.submit 'Submeter' %>
<% end %>

app/views/gyms/edit.html.erb
<h1>Editar</h1>

<%= render 'form', gym: @gym %>

<%= link_to 'Voltar', gyms_path %>

app/views/gyms/index.html.erb
<h1>Os meus escolhidos</h1>

<%= link_to '+ Adicionar', new_gym_path, class:"btn btn-success" %>

<div class="gym-cards">
  <% @gyms.each do |gym| %>
    <div class="gym-card">
      <div class="gym-card-info">
        <h2><%= gym.name %></h2>
        <p>Idas por mês: <%= gym.amount_of_times %></p>
      </div>
      <div class="gym-card-links">
        <%= link_to edit_gym_path(gym) do %><i class="fa-solid fa-pen" title="Editar"></i><% end %>
        <%= link_to gym_path(gym), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %><i class="fa-solid fa-trash-can" title="Apagar"></i><% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/gyms/new.html.erb
<h1>Novo</h1>

<%= render 'form', gym: @gym %>

<%= link_to 'Voltar', gyms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GymCheck</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to 'work', gyms_path, class:"btn btn-danger" %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to 'Home', gyms_path, class:"btn btn-success" %>
</div>